name: Docker Image CI

on:
  push:
  pull_request:
    branches: 
      - master
      - dev

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag mundhrakeshav/frontend
    - name: Export
      run: docker run mundhrakeshav/frontend Export CI=true
    - name: Run tests
      run: docker run mundhrakeshav/frontend npm run test
